// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRr-P4vfY9sU4TKjkCmaxL6e433T9W42U',
    appId: '1:1011008802284:web:679e0a0a439f51ee2fc4c9',
    messagingSenderId: '1011008802284',
    projectId: 'halomama-a2c83',
    authDomain: 'halomama-a2c83.firebaseapp.com',
    storageBucket: 'halomama-a2c83.firebasestorage.app',
    measurementId: 'G-QFBVBRBV2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBdtNToMwF5jm57w2OLhYPkLLosRX_So',
    appId: '1:1011008802284:android:424949b16e84a6532fc4c9',
    messagingSenderId: '1011008802284',
    projectId: 'halomama-a2c83',
    storageBucket: 'halomama-a2c83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlX9krxVhhS5r8vitTdx86wRzsfwQLCZ0',
    appId: '1:1011008802284:ios:9a2d6722f63e5f372fc4c9',
    messagingSenderId: '1011008802284',
    projectId: 'halomama-a2c83',
    storageBucket: 'halomama-a2c83.firebasestorage.app',
    iosBundleId: 'com.example.halomama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlX9krxVhhS5r8vitTdx86wRzsfwQLCZ0',
    appId: '1:1011008802284:ios:9a2d6722f63e5f372fc4c9',
    messagingSenderId: '1011008802284',
    projectId: 'halomama-a2c83',
    storageBucket: 'halomama-a2c83.firebasestorage.app',
    iosBundleId: 'com.example.halomama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRr-P4vfY9sU4TKjkCmaxL6e433T9W42U',
    appId: '1:1011008802284:web:bd3bc73e77d3f63d2fc4c9',
    messagingSenderId: '1011008802284',
    projectId: 'halomama-a2c83',
    authDomain: 'halomama-a2c83.firebaseapp.com',
    storageBucket: 'halomama-a2c83.firebasestorage.app',
    measurementId: 'G-WESX00YMHC',
  );
}
